name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test with ${{ matrix.env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - "3.13"
          - "3.12"
          - "3.11"
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install tox
        run: uv tool install --python 3.13 --python-preference only-managed tox --with tox-uv
      - name: Install Python
        if: matrix.env != '3.13'
        run: uv python install --python ${{ matrix.env }} --python-preference only-managed
      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false -e ${{ matrix.env }}
      - name: Run test suite
        run: tox run --skip-pkg-install -e ${{ matrix.env }}
